### PR TITLE
Build with OpenSSL 3 [skip ci]

### PR DESCRIPTION
**Pull request by JeanChristopheMorinPerso**
Build with OpenSSL 3 and pin host dependencies.

### CODE REVIEW

**Review by cbouss — APPROVED** [review]
LGTM

**Review by varlackc — COMMENTED** [review]
We probably might want to remove the `abs.yaml` file before merging to defaults.

**Comment by danpetry** [comment]
@varlackc do you have any remaining changes required to be addressed, or are you able to give this an approval if not?

**Review by ELundby45 — APPROVED** [review]

**Review by skupr-anaconda — APPROVED** [review]

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
